package domain;

public enum EventType {
    COMMIT_COMMENT_EVENT,
    CREATE_EVENT,
    DELETE_EVET,
    DISCUSSION_EVENT,
    FORK_EVENT,
    GOLLUM_EVENT,
    ISSUE_COMMENT_EVENT,
    ISSUE_EVENT,
    MEMBER_EVENT,
    PUBLIC_EVENT,
    PULL_REQUEST_EVENT,
    PULL_REQUEST_REVIEW_EVENT,
    PULL_REQUEST_REVIEW_COMMENT_EVENT,
    PUSH_EVENT,
    RELEASE_EVENT,
    WATCH_EVENT,
}
